name: GitHub Actions
on: 
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run production build
        run: npm run build:prod

      - name: Run ts lint
        run: npm run lint:ts

      - name: Run style lint
        run: npm run lint:scss

      - name: Run unit tests
        run: npm run test:unit